// Comprehensive Learning Assessment Tracks
// This file contains assessment problems for all core subjects

export interface Problem {
  id: string;
  title: string;
  description: string;
  type: string;
  difficultyLevel: number;
  tags: string[];
  category: string;
  estimatedTime: number;
  hints: string[];
  solution?: string;
  createdAt: Date;
  updatedAt: Date;
  createdBy: string;
  isActive: boolean;
  isAssessment: boolean;
  prerequisites?: string[];
  expectedAnswer?: string;
}

export const LEARNING_ASSESSMENTS: Problem[] = [
  // ========== ALGEBRA TRACK ==========
  {
    id: 'alg-1',
    title: 'Linear Equations - Basic',
    description: 'Solve for x: 3x + 7 = 22',
    type: 'math',
    difficultyLevel: 1,
    tags: ['algebra', 'linear', 'equations', 'basics'],
    category: 'Algebra',
    estimatedTime: 5,
    hints: ['What operation can you use to isolate x?', 'Remember to do the same thing to both sides'],
    solution: 'x = 5',
    expectedAnswer: '5',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
    createdBy: 'system',
    isActive: true,
    isAssessment: true,
    prerequisites: [],
  },
  {
    id: 'alg-2',
    title: 'Understanding Variables',
    description: 'Explain what a variable represents in an equation and why we use letters like x and y in algebra.',
    type: 'math',
    difficultyLevel: 1,
    tags: ['algebra', 'variables', 'comprehension'],
    category: 'Algebra',
    estimatedTime: 8,
    hints: ['Think about what unknowns are', 'Variables are placeholders'],
    expectedAnswer: 'variable placeholder unknown',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
    createdBy: 'system',
    isActive: true,
    isAssessment: true,
    prerequisites: ['alg-1'],
  },
  {
    id: 'alg-3',
    title: 'Systems of Equations',
    description: 'Solve the system: x + y = 10 and x - y = 2. What is the value of x?',
    type: 'math',
    difficultyLevel: 2,
    tags: ['algebra', 'systems', 'equations'],
    category: 'Algebra',
    estimatedTime: 10,
    hints: ['Try adding the two equations together', 'What happens when you add x - y to x + y?'],
    solution: 'x = 6',
    expectedAnswer: '6',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
    createdBy: 'system',
    isActive: true,
    isAssessment: true,
    prerequisites: ['alg-1', 'alg-2'],
  },
  {
    id: 'alg-4',
    title: 'Quadratic Equations',
    description: 'Solve: x² - 5x + 6 = 0. Give both solutions.',
    type: 'math',
    difficultyLevel: 3,
    tags: ['algebra', 'quadratic', 'factoring'],
    category: 'Algebra',
    estimatedTime: 12,
    hints: ['Try factoring', 'Look for two numbers that multiply to 6 and add to -5'],
    solution: 'x = 2 or x = 3',
    expectedAnswer: '2 3',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
    createdBy: 'system',
    isActive: true,
    isAssessment: true,
    prerequisites: ['alg-3'],
  },
  {
    id: 'alg-5',
    title: 'Exponential Growth Concept',
    description: 'Explain why compound interest grows faster than simple interest. What mathematical concept is at play?',
    type: 'math',
    difficultyLevel: 3,
    tags: ['algebra', 'exponential', 'comprehension', 'real-world'],
    category: 'Algebra',
    estimatedTime: 12,
    hints: ['Think about interest earning interest', 'Exponential vs linear growth'],
    expectedAnswer: 'exponential compound growth',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
    createdBy: 'system',
    isActive: true,
    isAssessment: true,
    prerequisites: ['alg-4'],
  },

  // ========== GEOMETRY TRACK ==========
  {
    id: 'geo-1',
    title: 'Area of a Rectangle',
    description: 'Find the area of a rectangle with length 8 cm and width 5 cm.',
    type: 'math',
    difficultyLevel: 1,
    tags: ['geometry', 'area', 'rectangle'],
    category: 'Geometry',
    estimatedTime: 5,
    hints: ['What formula calculates the area of a rectangle?'],
    solution: '40 cm²',
    expectedAnswer: '40',
    createdAt: new Date('2024-01-02'),
    updatedAt: new Date('2024-01-02'),
    createdBy: 'system',
    isActive: true,
    isAssessment: true,
    prerequisites: [],
  },
  {
    id: 'geo-2',
    title: 'Understanding Perimeter vs Area',
    description: 'Explain the difference between perimeter and area. Why do we measure them in different units?',
    type: 'math',
    difficultyLevel: 1,
    tags: ['geometry', 'perimeter', 'area', 'comprehension'],
    category: 'Geometry',
    estimatedTime: 8,
    hints: ['Perimeter is distance around', 'Area is space inside'],
    expectedAnswer: 'perimeter distance area space',
    createdAt: new Date('2024-01-02'),
    updatedAt: new Date('2024-01-02'),
    createdBy: 'system',
    isActive: true,
    isAssessment: true,
    prerequisites: ['geo-1'],
  },
  {
    id: 'geo-3',
    title: 'Pythagorean Theorem',
    description: 'A right triangle has legs of length 3 and 4. Find the length of the hypotenuse.',
    type: 'math',
    difficultyLevel: 2,
    tags: ['geometry', 'pythagorean', 'triangles'],
    category: 'Geometry',
    estimatedTime: 10,
    hints: ['Remember: a² + b² = c²', 'The hypotenuse is the longest side'],
    solution: '5',
    expectedAnswer: '5',
    createdAt: new Date('2024-01-02'),
    updatedAt: new Date('2024-01-02'),
    createdBy: 'system',
    isActive: true,
    isAssessment: true,
    prerequisites: ['geo-1', 'geo-2'],
  },
  {
    id: 'geo-4',
    title: 'Circle Area',
    description: 'A circle has a radius of 7 cm. What is its area? (Use π ≈ 3.14)',
    type: 'math',
    difficultyLevel: 2,
    tags: ['geometry', 'circles', 'area'],
    category: 'Geometry',
    estimatedTime: 8,
    hints: ['Area = πr²', 'Square the radius first'],
    solution: '153.86 cm²',
    expectedAnswer: '153.86',
    createdAt: new Date('2024-01-02'),
    updatedAt: new Date('2024-01-02'),
    createdBy: 'system',
    isActive: true,
    isAssessment: true,
    prerequisites: ['geo-3'],
  },
  {
    id: 'geo-5',
    title: 'Understanding Similar Triangles',
    description: 'Explain what it means for two triangles to be similar. How is this different from congruent?',
    type: 'math',
    difficultyLevel: 3,
    tags: ['geometry', 'triangles', 'similarity', 'comprehension'],
    category: 'Geometry',
    estimatedTime: 10,
    hints: ['Similar triangles have the same shape', 'Congruent means same size and shape'],
    expectedAnswer: 'same shape proportional angles',
    createdAt: new Date('2024-01-02'),
    updatedAt: new Date('2024-01-02'),
    createdBy: 'system',
    isActive: true,
    isAssessment: true,
    prerequisites: ['geo-4'],
  },

  // ========== CALCULUS TRACK ==========
  {
    id: 'calc-1',
    title: 'Understanding Limits',
    description: 'Explain in your own words what a limit means in calculus. Why is this concept important?',
    type: 'math',
    difficultyLevel: 3,
    tags: ['calculus', 'limits', 'comprehension'],
    category: 'Calculus',
    estimatedTime: 12,
    hints: ['Think about approaching a value', 'Limits describe behavior near a point'],
    expectedAnswer: 'approach value behavior',
    createdAt: new Date('2024-01-03'),
    updatedAt: new Date('2024-01-03'),
    createdBy: 'system',
    isActive: true,
    isAssessment: true,
    prerequisites: [],
  },
  {
    id: 'calc-2',
    title: 'Basic Limit Calculation',
    description: 'Find the limit: lim(x→2) of (3x + 4)',
    type: 'math',
    difficultyLevel: 2,
    tags: ['calculus', 'limits', 'calculation'],
    category: 'Calculus',
    estimatedTime: 8,
    hints: ['For continuous functions, just substitute the value', 'Plug in x = 2'],
    solution: '10',
    expectedAnswer: '10',
    createdAt: new Date('2024-01-03'),
    updatedAt: new Date('2024-01-03'),
    createdBy: 'system',
    isActive: true,
    isAssessment: true,
    prerequisites: ['calc-1'],
  },
  {
    id: 'calc-3',
    title: 'Understanding Derivatives',
    description: 'What does the derivative of a function represent? Give an example from real life.',
    type: 'math',
    difficultyLevel: 3,
    tags: ['calculus', 'derivatives', 'comprehension', 'real-world'],
    category: 'Calculus',
    estimatedTime: 12,
    hints: ['Derivatives measure rate of change', 'Think about speed and velocity'],
    expectedAnswer: 'rate change slope instantaneous',
    createdAt: new Date('2024-01-03'),
    updatedAt: new Date('2024-01-03'),
    createdBy: 'system',
    isActive: true,
    isAssessment: true,
    prerequisites: ['calc-2'],
  },
  {
    id: 'calc-4',
    title: 'Power Rule',
    description: 'Find the derivative of f(x) = x³',
    type: 'math',
    difficultyLevel: 3,
    tags: ['calculus', 'derivatives', 'power-rule'],
    category: 'Calculus',
    estimatedTime: 8,
    hints: ['Power rule: d/dx(xⁿ) = n·xⁿ⁻¹', 'Multiply by the exponent, then decrease it by 1'],
    solution: '3x²',
    expectedAnswer: '3x^2',
    createdAt: new Date('2024-01-03'),
    updatedAt: new Date('2024-01-03'),
    createdBy: 'system',
    isActive: true,
    isAssessment: true,
    prerequisites: ['calc-3'],
  },
  {
    id: 'calc-5',
    title: 'Understanding Integrals',
    description: 'Explain what an integral represents and how it relates to derivatives.',
    type: 'math',
    difficultyLevel: 4,
    tags: ['calculus', 'integrals', 'comprehension'],
    category: 'Calculus',
    estimatedTime: 15,
    hints: ['Integration is the reverse of differentiation', 'Think about area under a curve'],
    expectedAnswer: 'area accumulation antiderivative',
    createdAt: new Date('2024-01-03'),
    updatedAt: new Date('2024-01-03'),
    createdBy: 'system',
    isActive: true,
    isAssessment: true,
    prerequisites: ['calc-4'],
  },

  // ========== CHEMISTRY TRACK ==========
  {
    id: 'chem-1',
    title: 'Atoms and Elements',
    description: 'Explain what an atom is and how elements are defined by their atomic number.',
    type: 'science',
    difficultyLevel: 1,
    tags: ['chemistry', 'atoms', 'elements', 'comprehension'],
    category: 'Chemistry',
    estimatedTime: 8,
    hints: ['Atoms are the building blocks of matter', 'Atomic number = number of protons'],
    expectedAnswer: 'atom protons atomic number element',
    createdAt: new Date('2024-01-04'),
    updatedAt: new Date('2024-01-04'),
    createdBy: 'system',
    isActive: true,
    isAssessment: true,
    prerequisites: [],
  },
  {
    id: 'chem-2',
    title: 'Balancing Chemical Equations',
    description: 'Balance this equation: H₂ + O₂ → H₂O. How many of each molecule do you need?',
    type: 'science',
    difficultyLevel: 2,
    tags: ['chemistry', 'equations', 'balancing'],
    category: 'Chemistry',
    estimatedTime: 10,
    hints: ['Count atoms on each side', 'You need 2 hydrogen molecules and 1 oxygen molecule'],
    solution: '2H₂ + O₂ → 2H₂O',
    expectedAnswer: '2 1 2',
    createdAt: new Date('2024-01-04'),
    updatedAt: new Date('2024-01-04'),
    createdBy: 'system',
    isActive: true,
    isAssessment: true,
    prerequisites: ['chem-1'],
  },
  {
    id: 'chem-3',
    title: 'Understanding Ionic Bonds',
    description: 'Explain how ionic bonds form between atoms. What types of atoms tend to form ionic bonds?',
    type: 'science',
    difficultyLevel: 2,
    tags: ['chemistry', 'bonding', 'ionic', 'comprehension'],
    category: 'Chemistry',
    estimatedTime: 10,
    hints: ['Think about electron transfer', 'Metals and non-metals'],
    expectedAnswer: 'electron transfer metal nonmetal',
    createdAt: new Date('2024-01-04'),
    updatedAt: new Date('2024-01-04'),
    createdBy: 'system',
    isActive: true,
    isAssessment: true,
    prerequisites: ['chem-2'],
  },
  {
    id: 'chem-4',
    title: 'Molarity Calculation',
    description: 'If you dissolve 0.5 moles of NaCl in 2 liters of water, what is the molarity of the solution?',
    type: 'science',
    difficultyLevel: 3,
    tags: ['chemistry', 'solutions', 'molarity', 'calculation'],
    category: 'Chemistry',
    estimatedTime: 10,
    hints: ['Molarity = moles / liters', 'Divide 0.5 by 2'],
    solution: '0.25 M',
    expectedAnswer: '0.25',
    createdAt: new Date('2024-01-04'),
    updatedAt: new Date('2024-01-04'),
    createdBy: 'system',
    isActive: true,
    isAssessment: true,
    prerequisites: ['chem-3'],
  },
  {
    id: 'chem-5',
    title: 'Understanding pH',
    description: 'Explain what pH measures and why pH 7 is considered neutral.',
    type: 'science',
    difficultyLevel: 3,
    tags: ['chemistry', 'pH', 'acids', 'bases', 'comprehension'],
    category: 'Chemistry',
    estimatedTime: 10,
    hints: ['pH measures hydrogen ion concentration', 'pH 7 means equal H+ and OH-'],
    expectedAnswer: 'hydrogen ion concentration neutral',
    createdAt: new Date('2024-01-04'),
    updatedAt: new Date('2024-01-04'),
    createdBy: 'system',
    isActive: true,
    isAssessment: true,
    prerequisites: ['chem-4'],
  },

  // ========== PHYSICS TRACK ==========
  {
    id: 'phys-1',
    title: 'Understanding Force',
    description: 'Explain what force is and give three examples of forces in everyday life.',
    type: 'science',
    difficultyLevel: 1,
    tags: ['physics', 'force', 'comprehension'],
    category: 'Physics',
    estimatedTime: 8,
    hints: ['Force is a push or pull', 'Think about gravity, friction, applied force'],
    expectedAnswer: 'push pull gravity friction',
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-05'),
    createdBy: 'system',
    isActive: true,
    isAssessment: true,
    prerequisites: [],
  },
  {
    id: 'phys-2',
    title: 'Speed and Distance',
    description: 'A car travels at 60 mph for 2.5 hours. How far does it travel?',
    type: 'science',
    difficultyLevel: 2,
    tags: ['physics', 'motion', 'speed', 'calculation'],
    category: 'Physics',
    estimatedTime: 8,
    hints: ['Distance = Speed × Time', 'Make sure your units match'],
    solution: '150 miles',
    expectedAnswer: '150',
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-05'),
    createdBy: 'system',
    isActive: true,
    isAssessment: true,
    prerequisites: ['phys-1'],
  },
  {
    id: 'phys-3',
    title: 'Newton\'s Second Law',
    description: 'If a 10 kg object experiences a net force of 20 N, what is its acceleration?',
    type: 'science',
    difficultyLevel: 2,
    tags: ['physics', 'force', 'acceleration', 'newton'],
    category: 'Physics',
    estimatedTime: 10,
    hints: ['F = ma', 'Solve for a'],
    solution: '2 m/s²',
    expectedAnswer: '2',
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-05'),
    createdBy: 'system',
    isActive: true,
    isAssessment: true,
    prerequisites: ['phys-2'],
  },
  {
    id: 'phys-4',
    title: 'Understanding Energy Conservation',
    description: 'Explain the law of conservation of energy. Why can\'t we create or destroy energy?',
    type: 'science',
    difficultyLevel: 3,
    tags: ['physics', 'energy', 'conservation', 'comprehension'],
    category: 'Physics',
    estimatedTime: 12,
    hints: ['Energy can only change form', 'Total energy stays constant in a closed system'],
    expectedAnswer: 'conserved transform constant',
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-05'),
    createdBy: 'system',
    isActive: true,
    isAssessment: true,
    prerequisites: ['phys-3'],
  },
  {
    id: 'phys-5',
    title: 'Work and Energy',
    description: 'If you lift a 5 kg book 2 meters off the ground, how much work did you do? (g = 10 m/s²)',
    type: 'science',
    difficultyLevel: 3,
    tags: ['physics', 'work', 'energy', 'calculation'],
    category: 'Physics',
    estimatedTime: 10,
    hints: ['Work = Force × Distance', 'Force = mg for lifting against gravity'],
    solution: '100 J',
    expectedAnswer: '100',
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-05'),
    createdBy: 'system',
    isActive: true,
    isAssessment: true,
    prerequisites: ['phys-4'],
  },

  // ========== BIOLOGY TRACK ==========
  {
    id: 'bio-1',
    title: 'Cell Structure',
    description: 'What is the powerhouse of the cell and what does it do?',
    type: 'science',
    difficultyLevel: 1,
    tags: ['biology', 'cells', 'organelles'],
    category: 'Biology',
    estimatedTime: 5,
    hints: ['This organelle produces energy', 'It\'s often called the "powerhouse"'],
    solution: 'Mitochondria - produces ATP (energy) for the cell',
    expectedAnswer: 'mitochondria',
    createdAt: new Date('2024-01-06'),
    updatedAt: new Date('2024-01-06'),
    createdBy: 'system',
    isActive: true,
    isAssessment: true,
    prerequisites: [],
  },
  {
    id: 'bio-2',
    title: 'Understanding DNA',
    description: 'Explain what DNA is and why it\'s important for living organisms.',
    type: 'science',
    difficultyLevel: 2,
    tags: ['biology', 'DNA', 'genetics', 'comprehension'],
    category: 'Biology',
    estimatedTime: 10,
    hints: ['DNA stores genetic information', 'It\'s like an instruction manual'],
    expectedAnswer: 'genetic information instructions heredity',
    createdAt: new Date('2024-01-06'),
    updatedAt: new Date('2024-01-06'),
    createdBy: 'system',
    isActive: true,
    isAssessment: true,
    prerequisites: ['bio-1'],
  },
  {
    id: 'bio-3',
    title: 'Photosynthesis',
    description: 'What are the reactants and products of photosynthesis?',
    type: 'science',
    difficultyLevel: 2,
    tags: ['biology', 'photosynthesis', 'plants'],
    category: 'Biology',
    estimatedTime: 10,
    hints: ['What do plants need to make their own food?', 'What do plants release?'],
    solution: 'Reactants: CO2 + H2O + Light Energy. Products: Glucose + O2',
    expectedAnswer: 'carbon dioxide water light glucose oxygen',
    createdAt: new Date('2024-01-06'),
    updatedAt: new Date('2024-01-06'),
    createdBy: 'system',
    isActive: true,
    isAssessment: true,
    prerequisites: ['bio-2'],
  },
  {
    id: 'bio-4',
    title: 'Understanding Natural Selection',
    description: 'Explain Darwin\'s theory of natural selection. How do species evolve over time?',
    type: 'science',
    difficultyLevel: 3,
    tags: ['biology', 'evolution', 'natural-selection', 'comprehension'],
    category: 'Biology',
    estimatedTime: 12,
    hints: ['Survival of the fittest', 'Favorable traits are passed on'],
    expectedAnswer: 'survival traits adaptation evolution',
    createdAt: new Date('2024-01-06'),
    updatedAt: new Date('2024-01-06'),
    createdBy: 'system',
    isActive: true,
    isAssessment: true,
    prerequisites: ['bio-3'],
  },
  {
    id: 'bio-5',
    title: 'Ecosystem Energy Flow',
    description: 'Explain how energy flows through an ecosystem from producers to consumers to decomposers.',
    type: 'science',
    difficultyLevel: 3,
    tags: ['biology', 'ecology', 'energy-flow', 'comprehension'],
    category: 'Biology',
    estimatedTime: 12,
    hints: ['Start with the sun', 'Energy decreases at each level'],
    expectedAnswer: 'producers consumers decomposers food chain',
    createdAt: new Date('2024-01-06'),
    updatedAt: new Date('2024-01-06'),
    createdBy: 'system',
    isActive: true,
    isAssessment: true,
    prerequisites: ['bio-4'],
  },

  // ========== READING COMPREHENSION TRACK ==========
  {
    id: 'read-1',
    title: 'Identifying Main Ideas',
    description: 'Read this passage: "Dogs have been loyal companions to humans for thousands of years. They help with hunting, provide protection, and offer friendship. Different breeds have different traits, but all dogs share a common ancestor." What is the main idea?',
    type: 'language',
    difficultyLevel: 1,
    tags: ['reading', 'comprehension', 'main-idea'],
    category: 'Reading Comprehension',
    estimatedTime: 8,
    hints: ['What is the passage mostly about?', 'Look at the first sentence'],
    expectedAnswer: 'dogs companions humans',
    createdAt: new Date('2024-01-07'),
    updatedAt: new Date('2024-01-07'),
    createdBy: 'system',
    isActive: true,
    isAssessment: true,
    prerequisites: [],
  },
  {
    id: 'read-2',
    title: 'Making Inferences',
    description: 'Read this: "Sarah grabbed her umbrella as dark clouds gathered. She heard thunder in the distance." What can you infer is about to happen?',
    type: 'language',
    difficultyLevel: 2,
    tags: ['reading', 'comprehension', 'inference'],
    category: 'Reading Comprehension',
    estimatedTime: 8,
    hints: ['What do umbrellas protect against?', 'What do dark clouds and thunder mean?'],
    expectedAnswer: 'rain storm',
    createdAt: new Date('2024-01-07'),
    updatedAt: new Date('2024-01-07'),
    createdBy: 'system',
    isActive: true,
    isAssessment: true,
    prerequisites: ['read-1'],
  },
  {
    id: 'read-3',
    title: 'Understanding Context Clues',
    description: 'Read this: "The ancient artifact was fragile and could easily break into pieces if handled carelessly." What does "fragile" mean?',
    type: 'language',
    difficultyLevel: 2,
    tags: ['reading', 'vocabulary', 'context-clues'],
    category: 'Reading Comprehension',
    estimatedTime: 8,
    hints: ['Look at what happens to fragile things', 'They break easily'],
    expectedAnswer: 'easily broken delicate',
    createdAt: new Date('2024-01-07'),
    updatedAt: new Date('2024-01-07'),
    createdBy: 'system',
    isActive: true,
    isAssessment: true,
    prerequisites: ['read-2'],
  },
  {
    id: 'read-4',
    title: 'Analyzing Author\'s Purpose',
    description: 'Read this: "Studies show that regular exercise improves heart health, boosts mood, and increases energy. Start exercising today!" What is the author\'s purpose?',
    type: 'language',
    difficultyLevel: 3,
    tags: ['reading', 'comprehension', 'authors-purpose'],
    category: 'Reading Comprehension',
    estimatedTime: 10,
    hints: ['Is the author informing, persuading, or entertaining?', 'Look at the last sentence'],
    expectedAnswer: 'persuade convince',
    createdAt: new Date('2024-01-07'),
    updatedAt: new Date('2024-01-07'),
    createdBy: 'system',
    isActive: true,
    isAssessment: true,
    prerequisites: ['read-3'],
  },
  {
    id: 'read-5',
    title: 'Comparing and Contrasting',
    description: 'Compare these two sentences: "Cats are independent and groom themselves. Dogs are social and need regular baths." What is one key difference?',
    type: 'language',
    difficultyLevel: 2,
    tags: ['reading', 'comprehension', 'compare-contrast'],
    category: 'Reading Comprehension',
    estimatedTime: 10,
    hints: ['Look at their behaviors', 'Independent vs social'],
    expectedAnswer: 'independent social',
    createdAt: new Date('2024-01-07'),
    updatedAt: new Date('2024-01-07'),
    createdBy: 'system',
    isActive: true,
    isAssessment: true,
    prerequisites: ['read-4'],
  },

  // ========== ENGLISH LANGUAGE TRACK ==========
  {
    id: 'eng-1',
    title: 'Parts of Speech',
    description: 'In the sentence "The quick brown fox jumps over the lazy dog," identify the verb.',
    type: 'language',
    difficultyLevel: 1,
    tags: ['english', 'grammar', 'parts-of-speech'],
    category: 'English Language',
    estimatedTime: 5,
    hints: ['A verb is an action word', 'What is the fox doing?'],
    expectedAnswer: 'jumps',
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-08'),
    createdBy: 'system',
    isActive: true,
    isAssessment: true,
    prerequisites: [],
  },
  {
    id: 'eng-2',
    title: 'Subject-Verb Agreement',
    description: 'Choose the correct verb: "The team (is/are) playing well today."',
    type: 'language',
    difficultyLevel: 2,
    tags: ['english', 'grammar', 'subject-verb-agreement'],
    category: 'English Language',
    estimatedTime: 8,
    hints: ['Is "team" singular or plural?', 'Collective nouns are usually singular'],
    expectedAnswer: 'is',
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-08'),
    createdBy: 'system',
    isActive: true,
    isAssessment: true,
    prerequisites: ['eng-1'],
  },
  {
    id: 'eng-3',
    title: 'Understanding Metaphors',
    description: 'Explain what this metaphor means: "Time is money." Why do we say this?',
    type: 'language',
    difficultyLevel: 2,
    tags: ['english', 'figurative-language', 'metaphor'],
    category: 'English Language',
    estimatedTime: 10,
    hints: ['What do time and money have in common?', 'Both are valuable and limited'],
    expectedAnswer: 'valuable limited resource',
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-08'),
    createdBy: 'system',
    isActive: true,
    isAssessment: true,
    prerequisites: ['eng-2'],
  },
  {
    id: 'eng-4',
    title: 'Sentence Structure',
    description: 'Identify if this is a simple, compound, or complex sentence: "Although it was raining, we went to the park."',
    type: 'language',
    difficultyLevel: 3,
    tags: ['english', 'grammar', 'sentence-structure'],
    category: 'English Language',
    estimatedTime: 10,
    hints: ['Does it have one or more independent clauses?', 'Does it have a dependent clause?'],
    expectedAnswer: 'complex',
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-08'),
    createdBy: 'system',
    isActive: true,
    isAssessment: true,
    prerequisites: ['eng-3'],
  },
  {
    id: 'eng-5',
    title: 'Active vs Passive Voice',
    description: 'Convert this passive sentence to active voice: "The ball was thrown by Sarah."',
    type: 'language',
    difficultyLevel: 3,
    tags: ['english', 'grammar', 'voice'],
    category: 'English Language',
    estimatedTime: 10,
    hints: ['Make the subject do the action', 'Who is doing the throwing?'],
    expectedAnswer: 'Sarah threw the ball',
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-08'),
    createdBy: 'system',
    isActive: true,
    isAssessment: true,
    prerequisites: ['eng-4'],
  },
];

// Problem Bank problems (non-assessments for Socratic tutoring)
export const PROBLEM_BANK: Problem[] = [
  {
    id: 'prob-algebra-1',
    title: 'Exploring Linear Relationships',
    description: 'A train travels at a constant speed. After 2 hours, it has covered 150 miles. After 5 hours, it has covered 375 miles. How can we express the relationship between time and distance?',
    type: 'math',
    difficultyLevel: 2,
    tags: ['algebra', 'linear', 'relationships', 'real-world'],
    category: 'Math - Algebra',
    estimatedTime: 15,
    hints: ['Think about the rate of change', 'How much distance is covered per hour?'],
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-05'),
    createdBy: 'system',
    isActive: true,
    isAssessment: false,
    prerequisites: [],
  },
  {
    id: 'prob-geometry-1',
    title: 'Garden Design Problem',
    description: 'You want to create a rectangular garden with an area of 60 square meters. You have 32 meters of fencing to go around it. What should the dimensions be?',
    type: 'math',
    difficultyLevel: 3,
    tags: ['geometry', 'area', 'perimeter', 'problem-solving'],
    category: 'Math - Geometry',
    estimatedTime: 20,
    hints: ['Think about the formulas for area and perimeter', 'Can you set up two equations?'],
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-05'),
    createdBy: 'system',
    isActive: true,
    isAssessment: false,
    prerequisites: [],
  },
  {
    id: 'prob-physics-1',
    title: 'Falling Object',
    description: 'If you drop a ball from a tall building, it falls faster and faster. Why does this happen, and how would you describe its motion?',
    type: 'science',
    difficultyLevel: 2,
    tags: ['physics', 'gravity', 'motion', 'acceleration'],
    category: 'Science - Physics',
    estimatedTime: 15,
    hints: ['Think about forces acting on the ball', 'What does gravity do?'],
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-05'),
    createdBy: 'system',
    isActive: true,
    isAssessment: false,
    prerequisites: [],
  },
  {
    id: 'prob-biology-1',
    title: 'Photosynthesis Investigation',
    description: 'What are the reactants and products of photosynthesis?',
    type: 'science',
    difficultyLevel: 2,
    tags: ['biology', 'photosynthesis', 'plants', 'energy'],
    category: 'Science - Biology',
    estimatedTime: 15,
    hints: ['What do plants need to make their own food?', 'What do plants release?'],
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-05'),
    createdBy: 'system',
    isActive: true,
    isAssessment: false,
    prerequisites: [],
  },
  {
    id: 'prob-critical-thinking-1',
    title: 'The Bridge Problem',
    description: 'Four people need to cross a bridge at night. The bridge can only hold two people at a time. They have one flashlight and it must be carried across. Person A takes 1 minute to cross, B takes 2 minutes, C takes 5 minutes, and D takes 10 minutes. When two people cross together, they must go at the slower person\'s pace. What is the minimum time for all four to cross?',
    type: 'logic',
    difficultyLevel: 4,
    tags: ['logic', 'problem-solving', 'optimization', 'critical-thinking'],
    category: 'Critical Thinking',
    estimatedTime: 25,
    hints: ['Think about who should cross together', 'Consider sending the flashlight back with the fastest person'],
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-05'),
    createdBy: 'system',
    isActive: true,
    isAssessment: false,
    prerequisites: [],
  },
];


